### ISSUE TITLE
Write process to pull data from the GitHub public data set

### ISSUE THREAD

**Issue by mjpitz** [deps-cloud/deps-cloud-project#11]
BigQuery has a public dataset for a lot of GitHubs data: https://console.cloud.google.com/marketplace/browse?filter=solution-type:dataset&q=github&_ga=2.248962052.-2070301560.1556854657

We should be able to use this to build the foundation for a public dashboard that can be leveraged by the OpenSource community.

**Comment by parlad** [comment]
so you want some form of API (and dashboard) to view the changes that has to happen in a project? Or Just pull the activity information from a project using Google API?

**Comment by mjpitz** [comment]
So the API already exists (gateway [http] / tracker [grpc]). The deps-cloud/ui project is supposed to be the dashboard.

I actually just finished writing this tool yesterday. It bulk imports repository URL's from that dataset.

**Comment by mjpitz** [comment]
(Private) Repository URL: https://github.com/mjpitz/depscloud-bigquery-loader

It's a one off so I wasn't planning on completely opensourcing it.

**Comment by parlad** [comment]
sure
